# Generated by Django 3.1.4 on 2021-05-24 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210524_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
