# Generated by Django 3.2.1 on 2021-05-26 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.studentuser')),
            ],
        ),
    ]
